/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StringDisplay } from "./StringDisplay";
export * as factories from "./factories";
export { StringDisplay__factory } from "./factories/StringDisplay__factory";
